#! /bin/sh
#
#   ____ _____ ____ _       ____  ___   ______            _____
#   / __ ) ___// __ \ |     / /  |/  /  / ____/___  ____  / __(_)___ _
#  / __  \__ \/ /_/ / | /| / / /|_/ /  / /   / __ \/ __ \/ /_/ / __ `/
# / /_/ /__/ / ____/| |/ |/ / /  / /  / /___/ /_/ / / / / __/ / /_/ /
#/_____/____/_/     |__/|__/_/  /_/   \____/\____/_/ /_/_/ /_/\__, /
#                                                            /____/
#=====================================================================================
#================================================================================
#
# BSPWM configuration
# By Linbows (https://github.com/linbows)


# Switch keyboard layouts with alt+shift
setxkbmap -option grp:alt_shift_toggle us,ru,ua &

##=== Autostart ===##
sxhkd &
picom &
nitrogen --restore &
mpd --kill ; mpd &
~/.scripts/launch_polybar.sh
killall udiskie ; udiskie -t
killall nm-applet ; nm-applet &
killall blueman-applet ; blueman-applet &
killall dunst ; dunst &
#xautolock -time 5 -locker "betterlockscreen -l"
killall telegram-desktop ; telegram-desktop -startintray &
killall pulseeffects ; pulseeffects --gapplication-service &

##=== BSPWM Configuration ===##
bspc monitor -d 1 2 3 4 5 6 7 8
#bspc monitor -d 爵      

bspc config click_to_focus true
bspc config focus_follow_pointer false
bspc config window_gap 7
bspc config border_width 3
bspc config top_padding 28
bspc config bottom_padding 28

##=== Colors ===##
bspc config normal_border_color   "#7d7d7d"
bspc config active_border_color   "#7d7d7d"
bspc config focused_border_color  "#9c9c9c"
bspc config presel_feedback_color "#d0a011"
bspc config urgent_border_color   "#ca10d0"


##=== Rules ===##
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Mpv state=tiled