#! /bin/sh
#
#   ____ _____ ____ _       ____  ___   ______            _____
#   / __ ) ___// __ \ |     / /  |/  /  / ____/___  ____  / __(_)___ _
#  / __  \__ \/ /_/ / | /| / / /|_/ /  / /   / __ \/ __ \/ /_/ / __ `/
# / /_/ /__/ / ____/| |/ |/ / /  / /  / /___/ /_/ / / / / __/ / /_/ /
#/_____/____/_/     |__/|__/_/  /_/   \____/\____/_/ /_/_/ /_/\__, /
#                                                            /____/
#=====================================================================================
#================================================================================
#
# BSPWM configuration
# By cigash (https://github.com/cigash)

setxkbmap -option grp:shift_ctrl_toggle us,ru,ua &

##=== Autostart ===##
sxhkd &
picom &
nitrogen --restore &
mpd --kill ; mpd &
killall polybar ; polybar top &
killall udiskie ; udiskie -t

##=== BSPWM Configuration ===##
bspc monitor -d 1 2 3 4 5 6 7 8
bspc config click_to_focus true
bspc config focus_follow_pointer false
bspc config window_gap 7
bspc config border_width 2
bspc config top_padding 0
bspc config bottom_padding 0

##=== Colors ===##
bspc config normal_border_color "#7d7d7d"
bspc config focused_border_color "#004cff"


##=== Rules ===##
bspc rule -a emacs state=tiling
