#! /bin/sh
#
#   ____ _____ ____ _       ____  ___   ______            _____
#   / __ ) ___// __ \ |     / /  |/  /  / ____/___  ____  / __(_)___ _
#  / __  \__ \/ /_/ / | /| / / /|_/ /  / /   / __ \/ __ \/ /_/ / __ `/
# / /_/ /__/ / ____/| |/ |/ / /  / /  / /___/ /_/ / / / / __/ / /_/ /
#/_____/____/_/     |__/|__/_/  /_/   \____/\____/_/ /_/_/ /_/\__, /
#                                                            /____/
#=====================================================================================
#================================================================================
#
# BSPWM configuration
# By cigash (https://github.com/cigash)


# Switch keyboard layouts with shift+ctrl
setxkbmap -option grp:shift_ctrl_toggle us,ru,ua &

##=== Autostart ===##
sxhkd &
picom &
nitrogen --restore &
mpd --kill ; mpd &
~/.scripts/launch_polybar.sh
killall udiskie ; udiskie -t
killall nm-applet ; nm-applet &
killall blueman-applet ; blueman-applet &
xautolock -time 1 -locker "betterscreenlock -l"

##=== BSPWM Configuration ===##
bspc monitor -d 1 2 3 4 5 6 7 8
bspc config click_to_focus true
bspc config focus_follow_pointer false
bspc config window_gap 7
bspc config border_width 3
bspc config top_padding 28
bspc config bottom_padding 28

##=== Colors ===##
bspc config normal_border_color   "#7d7d7d"
bspc config active_border_color   "#7d7d7d"
bspc config focused_border_color  "#78dce8"
bspc config presel_feedback_color "#d0a011"
bspc config urgent_border_color   "#ca10d0"


##=== Rules ===##
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
